---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 30s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./apps"
  prune: true
  timeout: 30s
  postBuild:
    substitute:
      gitops_branch: production
      examiner_version: "~1.10.1"
      podinfo_version: "~6.3"
      examiner_message: "✨🎢 CloudLand 2023 R0ckX in Production 🎸✨"
      podinfo_message: "✨🎢 CloudLand 2023 R0ckX hard in Production 🎸✨"
