apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: examiner
  namespace: apps
spec:
  chart:
    spec:
      chart: application
      version: "~1"
      sourceRef:
        kind: HelmRepository
        name: chart-repo
        namespace: apps
      interval: 60m
  interval: 1m
  values:
    image:
      repository: quay.io/heubeck/examiner
      tag: 1.10.1 # {"$imagepolicy": "apps:examiner:tag"}
      tagSemverRange: ${examiner_version}
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 100Mi
    container:
      port: 8080
    livenessProbe:
      path: /.well-known/live
    readinessProbe:
      path: /.well-known/ready
    configuration:
      ECHO_VALUE: ${examiner_message}
    networkPolicy:
      egress: []
