---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- helm-repository.yaml
- examiner.yaml
- podinfo.yaml
- flux-image-update-automation.yaml
- ingress.yaml
