apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: apps
spec:
  chart:
    spec:
      chart: application
      version: "~1"
      sourceRef:
        kind: HelmRepository
        name: chart-repo
        namespace: apps
      interval: 60m
  interval: 1m
  values:
    image:
      repository: ghcr.io/stefanprodan/podinfo
      tag: 6.3.6 # {"$imagepolicy": "apps:podinfo:tag"}
      tagSemverRange: ${podinfo_version}
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 100Mi
    container:
      port: 9898
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
          - ALL
        add:
          - NET_BIND_SERVICE
    autoscaling:
      minReplicaCount: 2
      maxReplicaCount: 2
    livenessProbe:
      cmd: ['podcli', 'check', 'http', 'localhost:9898/healthz']
    readinessProbe:
      cmd: ['podcli', 'check', 'http', 'localhost:9898/readyz']
    configuration:
      PODINFO_UI_MESSAGE: ${podinfo_message}
      PODINFO_BACKEND_URL: "http://podinfo.apps/echo"
